services:
  - type: web
    name: autofill-gform-pro
    env: docker
    plan: free
    dockerFilePath: Dockerfile
    # Render will automatically pass correct PORT
    envVars:
      - key: AI_MODE
        value: grok
      - key: GROK_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
      - key: HEADLESS
        value: true

      - key: SLOW_MO
        value: 100
